Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using proyecto_ecommerce_.NET_MVC_.Models;

namespace proyecto_ecommerce_.NET_MVC_.Controllers
{
    [Authorize(AuthenticationSchemes =CookieAuthenticationDefaults.AuthenticationScheme ,Roles = "admin")]
    public class CategoriaController : BaseController
    {
        private readonly EcommerceNetContext _context;

        public CategoriaController(EcommerceNetContext ecommerceNetContext)
        {
            _context = ecommerceNetContext;
        }

        // GET: CategoriaController
        public async Task<IActionResult> Index(string buscar)
        {
            var categorias = from p in _context.Categorias select p;

            if (!String.IsNullOrEmpty(buscar))
            {
                categorias = categorias.Where(p => p.Nombre!.Contains(buscar));
            }

            return View(await categorias.ToListAsync());
        }

        // GET: CategoriaController/Details/5
        public async Task<IActionResult> Estado(int id)
        {
            try {
                var cat = await _context.Categorias.FindAsync(id);
                if (cat == null)
                    return NotFound();
                if(cat.Estado == "Activo") { 
                    cat.Estado = "Desactivado";
                }else
                    cat.Estado = "Activo";

                //guardamos en la BD
                _context.Update(cat);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            } catch {
                //mensaje de error que se mostrara en la vista con Toastr.js
                TempData["Message"] = "Ocurrió un error al actualizar el Estado.";
                TempData["MessageType"] = "error"; // success, error, info, warning
                throw;
            }
        }

        // GET: CategoriaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile img, Categoria categoria)
        {
            try
            {
                if (img != null && img.Length > 0)
                {
                    // Genera un nombre único para el archivo
                    var fileName = categoria.Nombre + Path.GetExtension(img.FileName);

                    // Ruta donde se guardará la imagen
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);

                    // Crea la carpeta "images" si no existe
                    Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images"));

                    // Guarda la imagen en la carpeta
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await img.CopyToAsync(stream);
                    }

                    // Guarda la ruta relativa en el modelo
                    categoria.Imagen = $"/images/{fileName}";
                }
                categoria.Estado = "Activo";

                _context.Add(categoria);
                await _context.SaveChangesAsync();

                TempData["Message"] = "Producto creado exitosamente.";
                TempData["MessageType"] = "success"; // success, error, info, warning

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["Message"] = "Ocurrió un error al crear la categoria.";
                TempData["MessageType"] = "error";
                throw;
            }
        }

        // GET: CategoriaController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var cat = await _context.Categorias.FindAsync(id);
            if (cat == null)
            {
                return NotFound();
            }
            return View(cat);
        }

        // POST: CategoriaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Categoria cat, IFormFile img)
        {
            try
            {
                if (cat.Id == null)
                    return NotFound();
                // Obtenemos el categoria original para manejar la imagen
                var catOriginal = await _context.Categorias.AsNoTracking().FirstOrDefaultAsync(c=> c.Id==cat.Id);
                if (catOriginal == null)
                    return NotFound();

                if(img != null && img.Length > 0)
                {
                    // Generamos un nuevo nombre para la imagen
                    var fileName = cat.Nombre + Path.GetExtension(img.FileName);
                    // Ruta donde se guardará la nueva imagen
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);
                    // Crea la carpeta "img" si no existe
                    Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images"));

                    // Guardamos la nueva imagen
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await img.CopyToAsync(stream);
                    }

                    // Eliminamos la imagen anterior del disco (si existe)
                    if (!string.IsNullOrEmpty(catOriginal.Imagen))
                    {
                        var oldFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", catOriginal.Imagen.TrimStart('/'));
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }

                    // Actualizamos la ruta de la imagen en el producto
                    cat.Imagen = $"/images/{fileName}";
                }else{
                    // Si no se sube una nueva imagen, mantenemos la existente
                    cat.Imagen = catOriginal.Imagen;
                }

                cat.Estado = catOriginal.Estado;
                // Actualizamos la categoria en la base de datos
                _context.Categorias.Update(cat);
                await _context.SaveChangesAsync();

                //mensaje de exito que se mostrara en la vista con Toastr.js
                TempData["Message"] = "Categoria actualizado exitosamente.";
                TempData["MessageType"] = "success"; // success, error, info, warning

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //mensaje de error que se mostrara en la vista con Toastr.js
                TempData["Message"] = "Ocurrió un error al actualizar la categoria.";
                TempData["MessageType"] = "error"; // success, error, info, warning
                throw;
            }
        }

    }
}

Controllers/ProductoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using proyecto_ecommerce_.NET_MVC_.Models;

using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace proyecto_ecommerce_.NET_MVC_.Controllers
{
    public class ProductoController : BaseController
    {
        private readonly EcommerceNetContext _context;

        public ProductoController(EcommerceNetContext ecommerceNetContext)
        {
            _context =ecommerceNetContext;
        }

        [Authorize(AuthenticationSchemes =CookieAuthenticationDefaults.AuthenticationScheme, Roles = "admin")]
        // GET: ProductoController
        public async Task<IActionResult> Index(string buscar)
        {
            var productos= from p in _context.Productos select p; 

            if (!String.IsNullOrEmpty(buscar))
            {
                productos = productos.Where(p => p.Nombre!.Contains(buscar));
            }

            return View(await productos.ToListAsync());
        }


        // GET: ProductoController/Details/5
        public async Task<IActionResult> Detail(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
         
            return View(producto);
        }

        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "admin")]
        // GET: ProductoController/Create
        public ActionResult Create()
        {
            var categorias =  _context.Categorias.ToList();
            if (categorias != null) { 
                ViewBag.categorias = categorias;
            }
            return View();
        }


        // POST: ProductoController/Create
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile img, Producto producto)
        {
            try
            {
                    if(img != null && img.Length > 0)
                    {
                        // Genera un nombre único para el archivo
                        var fileName = producto.Nombre + Path.GetExtension(img.FileName);

                        // Ruta donde se guardará la imagen
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);

                        // Crea la carpeta "img" si no existe
                        Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images"));

                        // Guarda la imagen en la carpeta
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await img.CopyToAsync(stream);
                        }

                        // Guarda la ruta relativa en el modelo
                        producto.Imagen = $"/images/{fileName}";
                    }
                //obtiene id de usuario desde el cookies
                string? idClaim = User.FindFirstValue("UsuarioCod");
                if (idClaim == null)
                {
                    TempData["Message"] = "Administrador no exise.";
                    TempData["MessageType"] = "warning";
                    return RedirectToAction("Login", "Login");
                }
                int? idUsu = int.Parse(idClaim);

                Usuario usuario = await _context.Usuarios.FindAsync(idUsu);
                if (usuario == null) {
                    return NotFound();
                }
                producto.Usuario = usuario;
                producto.Estado = "Activo";
                _context.Add(producto);
                await _context.SaveChangesAsync();
                
                TempData["Message"] = "Producto creado exitosamente.";
                TempData["MessageType"] = "success"; // success, error, info, warning

                return RedirectToAction(nameof(Index));
                
            }
            catch
            {
                TempData["Message"] = "Ocurrió un error al crear el producto.";
                TempData["MessageType"] = "error";
                throw;
            }
        }

        // GET: ProductoController/Edit/5
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
                return NotFound();

            var categorias = _context.Categorias.ToList();
            if (categorias != null)
            {
                ViewBag.categorias = categorias;
            }


            return View(producto);
        }

        // POST: ProductoController/Edit/5
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Producto producto, IFormFile img)
        {
            if (producto.Id == null)
            {
                return NotFound();
            }
            // Obtenemos el producto original para manejar la imagen
            var productoOriginal = await _context.Productos.AsNoTracking().FirstOrDefaultAsync(p => p.Id == producto.Id);

            if (productoOriginal == null)
            {
                return NotFound();
            }

            // Si se sube una nueva imagen
            if (img != null && img.Length > 0)
            {
                // Generamos un nuevo nombre para la imagen
                var fileName = producto.Nombre + Path.GetExtension(img.FileName);

                // Ruta donde se guardará la nueva imagen
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);

                // Crea la carpeta "img" si no existe
                Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images"));

                // Guardamos la nueva imagen
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await img.CopyToAsync(stream);
                }

                // Eliminamos la imagen anterior del disco (si existe)
                if (!string.IsNullOrEmpty(productoOriginal.Imagen))
                {
                    var oldFilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", productoOriginal.Imagen.TrimStart('/'));
                    if (System.IO.File.Exists(oldFilePath))
                    {
                        System.IO.File.Delete(oldFilePath);
                    }
                }

                // Actualizamos la ruta de la imagen en el producto
                producto.Imagen = $"/images/{fileName}";
            }
            else
            {
                // Si no se sube una nueva imagen, mantenemos la existente
                producto.Imagen = productoOriginal.Imagen;
            }
            // Actualizamos el producto en la base de datos
            try
            {
                producto.Estado = "Activo";
                producto.UsuarioId = productoOriginal.UsuarioId;
                _context.Productos.Update(producto);
                await _context.SaveChangesAsync();
                //mensaje de exito que se mostrara en la vista con Toastr.js
                TempData["Message"] = "Producto actualizado exitosamente.";
                TempData["MessageType"] = "success"; // success, error, info, warning
                return RedirectToAction(nameof(Index));
            }
            catch(DbUpdateConcurrencyException)
            {
                //mensaje de error que se mostrara en la vista con Toastr.js
                TempData["Message"] = "Ocurrió un error al actualizar el producto.";
                TempData["MessageType"] = "error"; // success, error, info, warning
                throw;
            }
        }

        // POST: ProductoController/Delete/5
        [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme, Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, IFormCollection collection)
        {
                var producto = await _context.Productos.FindAsync(id);

                if (producto == null)
                {
                    return NotFound();
                }

                bool estaEnUso = await _context.Detalles.AnyAsync(d => d.ProductoId == id && d.OrdenId != null);

            if (estaEnUso)
            {
                TempData["Message"] = "No se puede eliminar, el producto está en uso."; 
                TempData["MessageType"] = "info"; // success, error, info, warning
                return RedirectToAction(nameof(Index));
            }

            //elimina la imagen de la carpeta
            if (!string.IsNullOrEmpty(producto.Imagen))
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", producto.Imagen.TrimStart('/'));
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }
                }

          
                //elimina el producto de la base de datos
                _context.Productos.Remove(producto);
                await _context.SaveChangesAsync();
                //mensaje de exito que se mostrara en la vista con Toastr.js

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity;
@using System.Security.Claims;

@{
    var usuarioName=User?.FindFirstValue(ClaimTypes.Name) ?? "Login";
    var usuarioEmail = User?.FindFirstValue(ClaimTypes.Email) ?? "";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - proyecto_ecommerce_.NET_MVC_</title>

   

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/proyecto_ecommerce_.NET_MVC_.styles.css" asp-append-version="true" />
    <!------------- font awesome para iconos ---------------------------->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <!------ Toastr.js  para mostrar notificaciones -------------->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand-sm navbar-dark bg-dark nav-cabecera">
        <!-- Sidebar Toggle-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-controller="Home" asp-action="Index">ElectroShop</a>
        <!-- Navbar Search-->
        <!-- Navbar--> 
        <div class="collapse navbar-collapse" id="navbarTogglerDemo">
        <ul class="navbar-nav ms-auto me-0 me-md-3 my-2 my-md-0">
            <li class="nav-item">
                    <a class="nav-link active" href="@Url.Action("Carrito","Home")">
                        <i class="fas fa-cart-plus">(<label style="color: darkorange">@(ViewBag.CarritoCount ?? 0)</label>)</i>
                     Carrito</a>
            </li>
            <!--Poner -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        @usuarioName <i class="fas fa-user fa-fw"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-end text-center" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Correo del Usuario</a>
                    <li>@usuarioEmail</li>
                    <li><hr class="dropdown-divider" /></li>
                    @if (User.IsInRole("admin") || User.IsInRole("user"))
                    {
                        <li><a class="dropdown-item" asp-controller="Login" asp-action="CerrarSession">Cerrar sesion</a></li>
                    } else
                    {
                        <li><a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Login">Ingresar</a></li>
                    }

                </ul>
            </li>
        </ul>
        </div>
    </nav>
    <div class="cuerpo" >
        <div class="contenido-menu ">
            <div class="sb-sidenav-menu menu-container bg-dark">
                    <ul id="menu">
                        
                        <details>
                            <summary class="sb-sidenav-menu-heading">Resumen</summary>
                            <li>
                                <a class="nav-link" href="@Url.Action("Index","Home")">
                                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                    Dashboard
                                </a>
                            </li>
                            
						    @if (User.IsInRole("admin")) {
                            <!--<li>
							    <a class="nav-link" href="@Url.Action("Usuarios","Home")">
								    <div class="sb-nav-link-icon"><i class="fas fa-users"></i></div>
								    Usuarios
							    </a>
						    </li>
                            -->
                            }
                        </details>
                        @if (User.IsInRole("admin"))
                        {
                            <details>
                                <summary class="sb-sidenav-menu-heading">Mantenimiento</summary>
                                <li>
                                    <a class="nav-link" href="@Url.Action("Index","Categoria")">
                                        <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                        Categorias
                                    </a>
							    </li>
                                <li>
                                    <a class="nav-link" href="@Url.Action("Index","Producto")">
                                        <div class="sb-nav-link-icon"><i class="fas fa-boxes"></i></div>
                                        Productos
                                    </a>
                                </li>
                            </details>
                        }
                    @if (User.IsInRole("admin") || User.IsInRole("user"))
                    {
                        <details>
                            <summary class="sb-sidenav-menu-heading">Documentos</summary>
                            <li>
                            <a class="nav-link" asp-controller="Home" asp-action="ListaOrden">
                                <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                                Factura
                            </a>
                            </li>
                        </details>
                    }
                    
                    </ul>
                </div>
            <!-- <button class="salir" >✖️ Salir</button>-->
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; ElectroShop 2024</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!--Toastr.js  para mostrar notificaciones-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


<script>
    /*-------------Toastr.js  para mostrar notificaciones------------ */
    $(document).ready(function () {
        var message = '@TempData["Message"]';
        var messageType = '@TempData["MessageType"]'; // success, error, info, warning

        if (message) {
            toastr.options = {
                "closeButton": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "timeOut": "2000" // Duración de 2 segundos
            };

            toastr[messageType](message); // Muestra el mensaje
        }
    });
</script>

<script>
    /*-------------Toastr.js  para mostrar notificaciones------------ */
    $(document).ready(function () {
        var message = '@TempData["SuccessMessage"]';
        var messageType = '@TempData["MessageType"]'; // success, error, info, warning

        if (message) {
            toastr.options = {
                "closeButton": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "timeOut": "5000" // Duración de 5 segundos
            };

            toastr[messageType](message); // Muestra el mensaje
        }
    });
</script>

<script>
    /*-------------Toastr.js  para mostrar notificaciones------------ */
    $(document).ready(function () {
        var message = '@TempData["NuevoUsuario"]';
        var messageType = '@TempData["MessageType"]'; // success, error, info, warning

        if (message) {
            toastr.options = {
                "closeButton": true,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "timeOut": "8000" // Duración de 8 segundos
            };

            toastr[messageType](message); // Muestra el mensaje
        }
    });
</script>